#pragma once

#include "usb_types.h"

extern device_descriptor_t device_descriptor;

extern configuration_descriptor_t configuration_descriptor;

extern interface_association_descriptor_t interface_association_descriptor;

extern interface_descriptor_t video_control_interface_descriptor;

extern video_control_interface_descriptor_header_t
    video_control_interface_descriptor_header;

extern camera_terminal_descriptor_t camera_terminal_descriptor;

extern streaming_terminal_descriptor_t streaming_terminal_descriptor;

extern interface_descriptor_t video_streaming_interface_descriptor;

extern video_streaming_interface_descriptor_header_t
    video_streaming_interface_descriptor_header;

extern uncompressed_video_format_descriptor_t
    uncompressed_video_format_descriptor;

extern uncompressed_video_frame_descriptor_t
    uncompressed_video_frame_descriptor;

extern endpoint_descriptor_t video_streaming_endpoint_descriptor;

extern string_descriptor_t string_descriptor_zero;

extern string_descriptor_t string_descriptor_one;
